name = "TernaryQuartic"
version = "0.1.0"
keywords = ["math", "sos", "lean"]
defaultTargets = ["TernaryQuartic", "TernaryQuarticProof", "QuaternaryQuartic", "QuaternaryQuarticProof"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0"

[[lean_lib]]
name = "TernaryQuartic"

[[lean_lib]]
name = "TernaryQuarticProof"

[[lean_lib]]
name = "QuaternaryQuartic"

[[lean_lib]]
name = "QuaternaryQuarticProof"
